# Generated by Django 5.2.6 on 2025-09-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=80)),
                ('experience', models.CharField(max_length=50)),
                ('available', models.DateField()),
                ('terms', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False)),
            ],
        ),
    ]
