# Generated by Django 5.2.6 on 2025-09-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='available',
            new_name='availability',
        ),
        migrations.AlterField(
            model_name='form',
            name='terms',
            field=models.BooleanField(default=True),
        ),
    ]
